8.14. Открывается и закрывается + 8.15. Открывается и закрывается (ча…
htmlacademy-javascript/2200407-kekstagram-28 pull request #6
Opened 2023-03-25 14:58 UTC by AnnaMos8

…сть 2)

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +const bodyElement = document.querySelector('body');
Корневой узел `body` можно использовать напрямую через свойство `document.body`, без поиска и создания переменной.

> Это исключение для критерия Д21

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +const bodyElement = document.querySelector('body');
<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L6-L14
</details>

const body`Element` = document.querySelector('body');

<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L21
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L25
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L33
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L54
</details>

<details>
<summary>thumbnail.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/thumbnail.js#L12
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/thumbnail.js#L6
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/thumbnail.js#L23
</details>

<details>
<summary>gallery.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/gallery.js#L10
</details>

**и т.п.**

> См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/5#discussion_r1141123869

Повторю, что нужно _для всего проекта_ определиться с именованием переменных, которые указывают на DOM-элементы (= объекты типа `Element`). Если в одном случае был использовал суффикс `Element`, то его следует использовать для других переменных или просто не использовать.

[Д6](https://up.htmlacademy.ru/javascript/28/criteries#d6) 
> Используется единый стиль именования переменных

> если переменные, которые хранят DOM-элемент, содержат слово `Element` или любое другое, но одно и то же везде

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +let countCommentsRender;
Желательно задать значение по умолчанию (начальное значение) и очень желательно, чтобы его тип совпадал с типом актуального значения:

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L71

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +const renderComment = (comment) => {
<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L19-L41
</details>

Вместо полного (пере)создания элемента комментария следовало (пере)использовать _готовый_, например, в качестве шаблона:

<details>
<summary>index.htm</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/index.html#L159-L162
</details>

```js
const commentTemplateElement = bigPicture.querySelector('.social__comment').cloneNode(true);
```
Или добавить в документ с `index.html` шаблон с его разметкой:

```html
<template id="big-picture__comment">
 <li class="social__comment"> 
   <img class="social__picture" src="img/avatar-4.svg" alt="Аватар комментатора фотографии" width="35" height="35"> 
   <p class="social__text">Мега фото! Просто обалдеть. Как вам так удалось?</p> 
 </li> 
</template>
````
```js
const commentTemplateElement = document.querySelector('#big-picture__comment')
  .content
  .querySelector('social__comment');
```

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +  bigPictureCountComments.innerHTML = '';
bigPictureCountComments`.innerHTML = ''`;

См. [Element.`replaceChildren()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren#emptying_a_node):
> provides a very convenient mechanism for emptying a node of all its children. You call it on the parent node without any argument specified

```js
bigPictureCountComments.replaceChildren();
```

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +  fragmentCountCommentsElement.innerHtml += ' комментариев';
<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L46
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L59-L61
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L64
</details>

Неуместное и неправильное использование фрагмента.

```js
.textContent = `${countCommentsRender} из `
.innerHtml += ' комментариев';
```

Значение `5`  — это доч. _текстовой_ узел (= узел типа `#text`) и его можно изменять отдельно.

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/index.html#L157

Но проще всего в разметке обернуть это значение в `<span>` и в JS работать с ним, как с DOM-элементом, изменяя его содержание.

> Это всё равно не работает. См. другое замечание 😃

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +
<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L54
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L81
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L116
</details>

> См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/5#discussion_r1141124187

[Д21](https://up.htmlacademy.ru/javascript/28/criteries#d21) 
> Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +
<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L113-L114
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L123
</details>

`bigPictureClose`.addEventListener(`'click'`, on`CloseBigPicture`);
и т.п.

[Д4](https://up.htmlacademy.ru/javascript/28/criteries#d4)
> Название обработчика строится следующим образом:

> on + (на каком элементе) + `что случилось`:

2023-03-25 23:31 UTC, AlexMasterov commented on js/gallery.js
> +  picturesContainerElement.addEventListener('click', (evt) => {
Обращаю внимание, что повторный вызов функции `renderGallery` будет приводить к добавлению (накоплению) анон. обработчиков на элементе `'.pictures'`, что _далее_ может стать проблемой.

> См. критерий Б26

2023-03-25 23:31 UTC, AlexMasterov commented on js/gallery.js
> +      (item) => item.id === +thumbnail.dataset.thumbnailId
(item) => item.id === `+thumbnail.dataset.thumbnailId`

В цикле `.find` значение `thumbnail.dataset.thumbnailId`` не изменяется, но приводится к числу повторно, на _каждой_ итерации, что неэффективно и ухудшает читаемость.

2023-03-25 23:31 UTC, AlexMasterov commented on js/main.js
>  const allPhotos = generatePhotos();
const all`Photos` = generatePhotos();

Здесь объекты с данными фото названы `photos`.

<details>
<summary>gallery.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/gallery.js#L7
</details>

<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/big-picture.js#L112
</details>

Здесь уже `pictures`.

> В проекте нарушено единообразие в именование. См. критерий Д5

2023-03-25 23:31 UTC, AlexMasterov commented on js/gallery.js
> +      (item) => item.id === +thumbnail.dataset.thumbnailId
const `picture` = `pictures`.find(
  (`item`) => `item`.id === +thumbnail.dataset.thumbnailId

Название параметра коллбэка `.find` внезапно обобщается до `item`, хотя цикл по массиву с названием `pictures` 🤔

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/227747023-3712baf6-6431-4651-b868-935d5402b565.png)

![image](https://user-images.githubusercontent.com/700213/227747017-33c28f59-7885-4bb2-95e5-bc5f5c72a1c8.png)

</details>

<details>
<summary>Ожидание (index.html)</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/index.html#L157
</details>

Должно быть: "7 из 7 комментариев".

2023-03-25 23:31 UTC, AlexMasterov commented on js/big-picture.js
> +  bodyElement.classList.add('modal-open');
Пока элемент скрыт, то он не включен в рендеринге браузера и изменения его элементов не требуют учета.

Сейчас отображение большой фотографии (= снятие `hidden`) происходит _после_ всех изменений её элемента, что может хорошо сказаться на рендере 👍🏻

2023-03-25 23:41 UTC, AlexMasterov commented on js/util.js
> +const isEscapeKey = (evt) => evt.key === 'Escape';
Можно также учесть `Esc`:
```diff
- const isEscapeKey = (evt) => evt.key === 'Escape';
+ const isEscapeKey = ({ key }) => key.startsWith('Esc');
```

2023-03-25 23:42 UTC, AlexMasterov commented on js/util.js
> +const isEscapeKey = (evt) => evt.key === 'Escape';
В таком модуле допускается экспорт "по месту":
```diff
- const isEscapeKey = (evt) => evt.key === 'Escape';
+ export const isEscapeKey = (evt) => evt.key === 'Escape';
```

2023-03-25 23:43 UTC, AlexMasterov commented on js/util.js
<details>
<summary>util.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/util.js#L15
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/util.js#L31
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/98e8a9f7ca95cd30f57ec602ca5498a98b2db017/js/util.js#L50
</details>

Можно удалить.

[Б12](https://up.htmlacademy.ru/javascript/28/criteries#b12)
> В коде проекта нет файлов, модулей и частей кода, которые не используются, включая закомментированные участки кода

2023-03-25 23:50 UTC, AlexMasterov commented on js/util.js
> +const isEnterKey = (evt) => evt.key === 'Enter';
Это лишние и следует удалить.

[Б12](https://up.htmlacademy.ru/javascript/28/criteries#b12)
> В коде проекта нет файлов, модулей и частей кода, которые не используются, включая закомментированные участки кода

2023-03-26 18:51 UTC, AlexMasterov requested changes

2023-03-26 18:51 UTC, AlexMasterov commented on js/big-picture.js
> +  newAvatarPictureElement.height = AVATAR_SIZE;
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/680ee8c21200a6c08da930d08fb991671130c8ba/index.html#L213

width=`"35"` height=`"35"`

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/680ee8c21200a6c08da930d08fb991671130c8ba/js/big-picture.js#L30-L31

Это лишние и следует удалить.

2023-03-26 18:51 UTC, AlexMasterov commented on js/big-picture.js
> +    onBigPictureClose();
Обработчик событий нельзя использовать как обычную функцию, поскольку именование последних должно быть согласовано с критерием Б6, и наоборот, обычную функцию нельзя использовать в качестве обработчика событий, не нарушая Д4. Функции, которые названы в формате обработчиков событий DOM должны использоваться только для установки `.addEventListener` и вызываться браузером. 

Код `onBigPictureClose` следует вынести в отдельную обычную функцию и переиспользовать в коде и самих обработчиках.

[Б6](https://up.htmlacademy.ru/javascript/28/criteries#b6) 
> Название функции или метода содержит глагол [в начале]

[Д4](https://up.htmlacademy.ru/javascript/28/criteries#d4) 
> Именованные функции-обработчики событий названы в соответствии с правилами именования обработчиков

2023-03-26 18:51 UTC, AlexMasterov commented on js/gallery.js
> +    );
```js
 const picture = pictures.find(({ id }) => id === thumbnailId);
```

2023-03-26 18:52 UTC, AlexMasterov commented on js/big-picture.js
> +
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/680ee8c21200a6c08da930d08fb991671130c8ba/js/big-picture.js#L101

`bigPictureImgElement.querySelector('img')`.src

Нужно доработать.

2023-03-26 18:53 UTC, AlexMasterov commented on js/big-picture.js
> +
Ничего не исправлено.

Ожидание:

```diff
- bigPictureClose.addEventListener('click', onCloseBigPicture); 
+ bigPictureClose.addEventListener('click', onbBigPictureCloseClick); 
```

2023-03-26 18:55 UTC, AlexMasterov commented on js/big-picture.js
> +    onBigPictureClose();
См. также https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/6#discussion_r1148618773.

2023-03-28 17:05 UTC, AnnaMos8 commented on js/gallery.js
> +  picturesContainerElement.addEventListener('click', (evt) => {
Пока не совсем поняла, как это исправить. Брала пример из ретро. Надеюсь на совет, либо потом буду исправлять в процессе.

2023-03-28 17:23 UTC, AnnaMos8 commented
Почему то сначала не видела все комментарии по доработкам. Поэтому пришлось делать несколько коммитов с доработками. Надеюсь теперь все.

2023-03-29 00:57 UTC, AlexMasterov commented on js/big-picture.js
> +  commentsButtonLoaderElement.addEventListener('click', onLoadMoreComments);
См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/6#discussion_r1148618773:

```diff
- commentsButtonLoaderElement.addEventListener('click', onLoadMoreComments);
+ commentsButtonLoaderElement.addEventListener('click', onCommentsButtonLoaderClick);
```

2023-03-29 00:59 UTC, AlexMasterov commented on js/big-picture.js
> +  document.addEventListener('keydown', onBigPictureEscPress);
```diff
- document.addEventListener('keydown', onBigPictureEscPress);
+ document.addEventListener('keydown', onDocumentEscKeydown);
```
> document.addEventListener('keydown', onDocumentKeydown);

2023-03-29 01:00 UTC, AlexMasterov commented on js/big-picture.js
> +  bigPictureCloseElement.removeEventListener('click', onBigPictureCloseClick);
> 'onBigPictureEscPress' was used before it was defined  
> 'onBigPictureCloseClick' was used before it was defined

[Б11](https://up.htmlacademy.ru/javascript/28/criteries#b11)
> Код соответствует стилю оформления, принятому на проекте

2023-03-29 01:00 UTC, merged