9.14. Правда или действие + 9.16. Помощь друга
htmlacademy-javascript/2200407-kekstagram-28 pull request #7
Opened 2023-04-02 12:07 UTC by AnnaMos8

Сделала два 9-ых задания. Проверь пожалуйста.

2023-04-02 13:51 UTC, AlexMasterov requested changes

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +const onScaleControlChange = function (evt) {
const onScaleControlChange = `function` (evt) {

[Д5](https://up.htmlacademy.ru/javascript/28/criteries#d5) 
> Все функции объявлены единообразно

> При объявлении функций используются стрелочные функции

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +  if (typeEffect !== 'NONE') {
if (typeEffect !== `'NONE'`) {

Для этой строки, которая используется в логике, могут попросить создать "константу".

Б7, ~Д19

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +    sliderValueElement.value = null;
sliderValueElement`.value` = `null`;

<details>
<summary>null</summary>

![image](https://user-images.githubusercontent.com/700213/229353777-e2f2739f-2f8d-40ce-a420-2a71338118d8.png)

</details>

> `null` = no (_object_) value

Разве тип значения `.value` является объектом 🤔

```js
typeof sliderValueElement.value // string
```
Желательно задать значение по умолчанию с учетом спецификации и в рамках одного типа `string`, не полагаясь на неявные приведения типов.

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +  picturePreviewElement.style.filter = `${effectCurrent}(${valueCurrent + unitCurrent})`;
```js
typeof valueCurrent // string
typeof unitCurrent // string
```

${valueCurrent `+` unitCurrent}

Обращаю внимание, что оператор `+` используется для конкатенации строки внутри шаблонных строк.

**JS2**-Б33
> Внутри шаблонов-строк (template literals) не используется конкатенация строк

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +  picturePreviewElement.style = '';
picturePreviewElement`.style = ''`;

Страшно.

См. [HTMLElement`.style`](HTMLElement.style)
> This property is read-only, meaning it is not possible to assign a `CSSStyleDeclaration` object to it

> Using style in this manner will completely overwrite all inline styles on the element

~Д8, ~Д9

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +  picturePreviewElement.className = ''; // сбрасываем классы, чтобы не накапливались перед измененением
Таким образом будут стерты (и потеряны) _все_ CSS-классы, а не только классы для фильтров.

На защите _могут_ придраться к столь небезопасным решениям.

[Д23.](https://up.htmlacademy.ru/javascript/28/criteries#d23)
> Изменения применяются точечно.

> Например, при удалении классов с DOM-элемента, не производится попытка удалить все возможные классы, если можно убрать лишь тот, который действительно установлен на DOM-элементе в данный момент

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +  effectsListElement.addEventListener('change', onEffectItemChange);
`effectsList`Element + `change` !== on`EffectItem`Change

На защите проекта _могут_ придраться к именованию.

[Д4](https://up.htmlacademy.ru/ecmascript/20/criteries#d4)
> on + `(на каком элементе)` + что случилось

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +  scaleControlBiggerElement.addEventListener('click', onScaleControlChange);
`scaleControlSmaller`Element + `click` !== on`ScaleControlChange`
`scaleControlBigger`Element + `click` !== on`ScaleControlChange`

См.:
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/6#discussion_r1148618773
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/6#discussion_r1151291276

[Д4](https://up.htmlacademy.ru/ecmascript/20/criteries#d4)
> on + `(на каком элементе)` + `что случилось`

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +    scale /= 100;
`100`, `25`

[Д19](https://up.htmlacademy.ru/javascript/28/criteries#d19) 
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +const EFFECTS_PARAMS = {
<details>
<summary>form-effects.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/81a41dccf5e4118ce0ecb7db90323e2969f2a483/js/form-effects.js#L104
</details>

Объект используется в роле словаря, но назван в формате... непонятно в каком (перечисление?).

<details>
<summary>Пример в Б8 и слайды</summary>

![image](https://user-images.githubusercontent.com/700213/229353708-7dade022-e4cb-48cc-992d-4d9bab0e6d26.png)

![image](https://user-images.githubusercontent.com/700213/229355220-7c273f5c-049a-4d8a-b46d-c6cd8e92809a.png)


</details>

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +const updateParamsSlider = (min = 0, max = 100, step = 1) => {
```diff
- updateParamsSlider
+ updateSliderParams
```

2023-04-02 13:51 UTC, AlexMasterov commented on js/big-picture.js
> `onBigPictureCloseClick' **was used before it was defined**
> 'onDocumentEscKeydown' **was used before it was defined**  

См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/6#discussion_r1151291787 (не исправлено)

`const` onCommentsButtonLoaderClick = `() =>` {

`const` означает, что значение переменной будет инициализировано (активировано) по месту объявлению и до этого момента переменная находится в т.н. "временной мертвой зоне" (TDZ). В случае прямого использование такой переменной до объявления будет ошибка `ReferenceError`, но их использование для `addEventListener` создает лишь неопределенное поведение, что не нравится линтеру.

Нужно изменить код, чтобы такие переменные с `const` использовались после объявления или объявить обработчики с помощью `function`, которые активируются частично и могут быть доступны сразу.

[Б11](https://up.htmlacademy.ru/javascript/28/criteries#b11)
> Код соответствует стилю оформления, принятому на проекте

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +    updateParamsSlider(EFFECTS_PARAMS?.[typeEffect]?.MIN, EFFECTS_PARAMS?.[typeEffect]?.MAX, EFFECTS_PARAMS?.[typeEffect]?.STEP);
EFFECTS_PARAMS`?.`[typeEffect]`?.`

Неудачный дизайн словаря (и решение в целом), если его использования требуется проверок `?.` 🤔

2023-04-02 13:51 UTC, AlexMasterov commented on js/form-effects.js
> +      min: min,
const updateParamsSlider = (`min` = 0, max = 100, step = 1) => {

В таком случае ES6 (2015) позволяет упростить создание свойств объекта:
```diff
- min: min,
+ mim,
```

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +    closeEditPictureForm();
> 'closeEditPictureForm' was used before it was defined

Ошибки линтера следует исправить _до_ отправки на проверку.

[Б11](https://up.htmlacademy.ru/javascript/28/criteries#b11)
> Код соответствует стилю оформления, принятому на проекте

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +  uploadPictureInputElement.addEventListener('change', onFileUploadChange);
`uploadPictureInput`Element + `change` !== on`FileUpload`Change

[Д4](https://up.htmlacademy.ru/ecmascript/20/criteries#d4)
> on + `(на каком элементе)` + что случилось

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +  pictureCloseButtonElement.addEventListener('click', onEditPictureCloseButtonClick);
`pictureCloseButton`Element + `click` !== on`EditPictureCloseButton`Click

[Д4](https://up.htmlacademy.ru/ecmascript/20/criteries#d4)
> on + `(на каком элементе)` + что случилось

2023-04-02 13:51 UTC, AlexMasterov commented on js/show-message.js
> +let successMessageClone;
[Д6](https://up.htmlacademy.ru/ecmascript/20/criteries#d6) 
> Используется единый стиль именования переменных

> если есть переменные, которые хранят DOM-элемент и содержат слово Element, то это правило работает везде

2023-04-02 13:51 UTC, AlexMasterov commented on js/show-message.js
> +
> 'removeErrorMessage' was used before it was defined  
> 'removeSuccessMessage' was used before it was defined
> 'removeErrorMessage' was used before it was defined  
> 'removeSuccessMessage' was used before it was defined

[Б11](https://up.htmlacademy.ru/javascript/28/criteries#b11)
> Код соответствует стилю оформления, принятому на проекте

2023-04-02 13:51 UTC, AlexMasterov commented on js/show-message.js
> +  document.addEventListener('keydown', onErrorMessageKeydown);
`document` + `keydown` !== on`ErrorMessage`Keydown

> См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/6#discussion_r1151291276

С учетом последнего обсуждения этого критерия _могут_ придраться на защите.

[Д4](https://up.htmlacademy.ru/ecmascript/20/criteries#d4)
> on + `(на каком элементе)` + что случилось

2023-04-02 13:51 UTC, AlexMasterov commented on js/show-message.js
> +  document.addEventListener('keydown', onSuccessMessageKeydown);
`document` + `keydown` !== on`SuccessMessage`Keydown

[Д4](https://up.htmlacademy.ru/ecmascript/20/criteries#d4)
> on + `(на каком элементе)` + что случилось

2023-04-02 13:51 UTC, AlexMasterov commented on js/show-message.js
> +export { createErrorMessage, createSuccessMessage };
Код обоих функций почти отличается только названием.

На защите _могут_ придраться к степени дублирования кода в модуле.

[Д14](https://up.htmlacademy.ru/javascript/28/criteries#d14) 
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +    picturePreviewElement.src = URL.createObjectURL(file);
См. [URL.`createObjectURL()`](https://developer.mozilla.org/ru/docs/Web/API/URL/createObjectURL#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F):
> При каждом вызове `createObjectURL()`, создаётся новый URL объект, даже если он уже был ранее создан для того же самого объекта. Память для каждого из них нужно освобождать с помощью [URL.`revokeObjectURL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL), в том случае, если они больше не нужны. Браузер сделает это автоматически с выгрузкой объекта, тем не менее в целях оптимизации производительности и использования памяти, следует принудительно выгружать их по возможности

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +  document.body.classList.remove('modal-open');
> См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/6#discussion_r1148448843 (осталось без понимания)

По коду сначала "сбрасывается" форма, а только потом происходит её скрытие. Таким образом, рендер браузера должен учесть и отобразить избыточные изменения формы.

Лучше скрыть форму сразу.

[Б25](https://up.htmlacademy.ru/javascript/28/criteries#b25) 
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/229356467-643195c7-b03c-460d-9489-c5249ced95b9.png)
![image](https://user-images.githubusercontent.com/700213/229356485-ec7b4eec-7a5b-4036-8e3e-d149c323e9f9.png)


</details>

При использование масштабирования фото у значения поля пропадает `%`.

Нужно поправить.

2023-04-02 13:51 UTC, AlexMasterov commented on js/show-message.js
> +
См. ТЗ:
> Сообщение должно исчезать <...> по клику на произвольную область экрана **за пределами блока с сообщением**

Сейчас сообщение можно закрыть только по `Esc` и клику на кнопку закрытия ("Круто", "Попробовать еще").

Нужно доработать закрытие "по клику на произвольную область экрана за пределами блока с сообщением".


<details>
<summary>Блоки с сообщением</summary>

`.success__inner`
`.error__inner`

Так было давно согласовано с авторами курса и чаще всего требуется на защите, но можно оставить на усмотрение случайного проверяющего
</details>

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +    createErrorMessage(FILE_TYPES_ERROR_MESSAGE);
Функция может создавать сообщение неявно, но при её использовании этим не пользуются (она ничего не возвращает). Таким образом, она _показывает_ сообщение,

2023-04-02 13:51 UTC, AlexMasterov commented on js/form.js
> +  submitButtonElement.disabled = !submitButtonElement.disabled;
`block`SubmitButton + `!submitButtonElement.disabled`

Функция не только блокирует, но и разблокирует, являясь, по сути, переключателем (`toggle`) с _непредсказуемым_ значением `disabled`.

> Неудачное название функции и плохой (опасный) дизайн

~Б6

2023-04-02 17:11 UTC, AnnaMos8 commented on js/big-picture.js
Так можно обработчики мне объявить с помощью function, чтобы не ругался линтер. А остальные я оставлю стрелочными, такое пойдет при проверке ?

2023-04-02 17:22 UTC, AlexMasterov commented on js/big-picture.js
> Так можно обработчики мне объявить с помощью function, чтобы не ругался линтер. А остальные я оставлю стрелочными, такое пойдет при проверке ?

Да.

См. Д5:
> Объявление функций как «[функциональное выражение](https://up.htmlacademy.ru/javascript/28/book/basic-js/function)» либо как «[функциональное объявление](https://up.htmlacademy.ru/javascript/28/book/basic-js/function)» допускается в случаях, когда нужно использовать контекст функции или поднятие (hoisting)

2023-04-03 18:31 UTC, AnnaMos8 commented on js/form.js
> +    picturePreviewElement.src = URL.createObjectURL(file);
пока не поняла как нужно освобождать память, ведь с объектом мы еще не закончили работу (а его еще нужно отправлять на сервер)

2023-04-03 20:03 UTC, AlexMasterov commented on js/form-effects.js
> +const EFFECTS_NONE = 'NONE';
[Б10.](https://up.htmlacademy.ru/javascript/28/criteries#b10) 
> Список констант идёт перед основным кодом

2023-04-03 20:03 UTC, AlexMasterov commented on js/form-effects.js
>    CHROME: {
```diff
- const effectSettings = {
+ const effectToSettings = {
```
Название всех ключей объекта нужно записать в `camelCase`:
```diff
- CHROME: {
+ chrome: {
```
и т.п.

2023-04-03 20:03 UTC, AlexMasterov commented on js/show-message.js
> +const MESSAGE_TYPES_SUCCESS = 'success';
MESSAGE_TYPE`S`_ERROR 

Множ. число.

```js
const MessageType = {
  ERROR: 'error',
  SUCCESS: 'success',
};
```

2023-04-03 20:04 UTC, AlexMasterov commented on js/form.js
> +    picturePreviewElement.src = URL.createObjectURL(file);
Можно удалить при закрытии формы:
```js
URL.revokeObjectURL(picturePreviewElement.src);
picturePreviewElement.src = '';
```

2023-04-03 20:04 UTC, merged