11.14. Надо подкачаться
htmlacademy-javascript/2200407-kekstagram-28 pull request #8
Opened 2023-04-06 18:30 UTC by AnnaMos8

2023-04-06 18:36 UTC, AnnaMos8 commented
Мне пришлось сделать в этой ветке задание по взаимодействию с сервером"11.14. Надо подкачаться" , так как мне писало что я не завершила предыдущее в интерфейсе htmlacademy (я делала в одной ветке два задания, чтобы успеть к защите). Проверь пожалуйста.

2023-04-06 20:06 UTC, AlexMasterov requested changes

2023-04-06 20:06 UTC, AlexMasterov commented on js/backend.js
> +const BODY_NULL = null;
const BODY`_NULL` = `null`;

Зачем 🤔

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/ad450f6def1f20b0733fddc0e688856ea1d1f788/js/form-effects.js#L4

Тоже самое.

2023-04-06 20:06 UTC, AlexMasterov commented on js/backend.js
> +  SEND_DATA: '',
GET`_DATA`: `'/data'`,
SEND`_DATA`: '',

Неудачное название перечисления и ключей.

<details>
<summary>JS2-Б16</summary>

![image](https://user-images.githubusercontent.com/700213/230483035-403676ae-ee44-4b0f-a04b-38bf60fe4092.png)

</details>

2023-04-06 20:06 UTC, AlexMasterov commented on js/backend.js
> +  SEND_DATA: 'Не удалось отправить данные в форме. Попробуйте ещё раз',
GET`_DATA`
SEND`_DATA`

2023-04-06 20:06 UTC, AlexMasterov commented on js/backend.js
> +  fetch(BASE_URL + route, { method, body })
BASE_URL `+` route

См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/7#discussion_r1155302740.

2023-04-06 20:06 UTC, AlexMasterov commented on js/form-effects.js
> +const SCALE_MIN = 25;
const `SCALE_`STEP = 25;
const `SCALE_`MAX = 100;
const `SCALE_`MIN = 25;

<details>
<summary>JS2-Б16</summary>

![image](https://user-images.githubusercontent.com/700213/230483035-403676ae-ee44-4b0f-a04b-38bf60fe4092.png)

</details>

```js
ScaleValue.STEP
ScaleValue.MAX
ScaleValue.MIN
```
> `ControlScale.STEP` и т.п.

2023-04-06 20:06 UTC, AlexMasterov commented on js/form.js
>  const FILE_TYPES_ERROR_MESSAGE = 'Допустимы только файлы изображений: gif, png, jpeg, jpg';
```diff
- 'Допустимы только файлы изображений: gif, png, jpeg, jpg';
+ 'Допустимы только файлы изображений: '.concat(FILE_TYPES.join(', '));
```
> \`Допустимы только файлы изображений: ${FILE_TYPES.join(', ')}\`;

2023-04-06 20:06 UTC, AlexMasterov commented on js/gallery.js
> +const renderGallery = (pictures) => pictures.forEach((picture) => renderThumbnail(picture));
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/ad450f6def1f20b0733fddc0e688856ea1d1f788/js/gallery.js#L28
https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/ad450f6def1f20b0733fddc0e688856ea1d1f788/js/gallery.js#L24

Узел элемента `picturesContainerElement` находится в DOM (1) и там видим (2), добавление в него элемент, тем более в цикле, может привести к избыточным перерисовкам страницы.

> См. снова https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/7#discussion_r1155312533

Для вставки нужно использовать фрагмент, явно или неявно

> последние требует значения DOM API

[Б25.](https://up.htmlacademy.ru/javascript/28/criteries#b25)
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

2023-04-06 20:06 UTC, AlexMasterov commented on js/show-message.js
> +  messageCloneElement = typeMessage === MessageType.ERROR ? errorTemplateElement.cloneNode(true) : successTemplateElement;
`successTemplateElement`, в отличие от `errorTemplateElement`, используется напрямую, без клонирования.

2023-04-06 20:06 UTC, AlexMasterov commented on js/gallery.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/230479319-69083935-5bb4-4dec-9f7a-5b20eef36a81.png)

</details>

Желательно поправить разметку.

2023-04-06 20:06 UTC, AlexMasterov commented on js/form-effects.js
<details>
<summary>form-effects.js</summary>

https://github.com/htmlacademy-javascript/2200407-kekstagram-28/blob/ad450f6def1f20b0733fddc0e688856ea1d1f788/js/form-effects.js#L145
</details>

 sliderValueElement`.value = null`; 

См. https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/7#discussion_r1155301642.

2023-04-06 20:06 UTC, AlexMasterov commented on js/show-message.js
> +  if (evt.target.closest('.error__button') || evt.target.matches('.error') || evt.target.closest('.success__button') || evt.target.matches('.success')) {
> См. снова https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/7#discussion_r1155314444

См. ТЗ:

> Сообщение должно исчезать <...> по клику на произвольную область экрана <ins>за пределами _блока_ с сообщением</ins>

Не реализовано.

Сейчас "сообщение" можно закрыть по клику за пределами его границы его окна, а не блока с текстом сообщения.

> Можем оставить на усмотрение случайного проверяющего

2023-04-06 20:06 UTC, AlexMasterov commented on js/show-message.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/230482307-26323612-49ac-407f-a5f0-692511913766.png)

</details>

Сейчас форма редактирования изображения закрывается в случае неуспешной отправки, например, в отсутствии сети.

См. ТЗ:
> **При успешной отправке** формы форма редактирования изображения закрывается

> Если при отправке данных произошла ошибка запроса, нужно показать соответствующее сообщение. <...> **В таком случае вся введённая пользователем информация сохраняется, чтобы у него была возможность отправить форму повторно**

2023-04-07 18:45 UTC, AnnaMos8 commented on js/backend.js
> +const BODY_NULL = null;
Ты советовал тогда вот это https://github.com/htmlacademy-javascript/2200407-kekstagram-28/pull/7#discussion_r1155301533 , что попросят по критериям создать константу. Я думала что и в этом месте тогда создам ее. Но хорошо, тогда уберу если все таки не нужно.

2023-04-08 00:33 UTC, AlexMasterov commented on js/show-message.js
> +  messageCloneElement = typeMessage === MessageType.ERROR ? errorTemplateElement.cloneNode(true) : successTemplateElement.cloneNode(true);
```js
messageCloneElement = (typeMessage === MessageType.ERROR ? errorTemplateElement : successTemplateElement).cloneNode(true);
```
```js
const templateElement = typeMessage === MessageType.ERROR ? errorTemplateElement : successTemplateElement;

messageCloneElement = templateElement.cloneNode(true);
```

2023-04-08 00:34 UTC, merged